# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rcov_plugin}
  s.version = "3.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.6") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Alan Johnson}, %q{Luca Invernizzi}]
  s.date = %q{2011-09-06}
  s.description = %q{rcov_plugin adds the rake tasks that you need to measure coverage in your Rails project}
  s.email = [%q{alan@commondream.net}, %q{invernizzi.l@gmail.com}]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "lib/rcov_plugin.rb",
    "lib/rcov_plugin/railtie.rb",
    "lib/tasks/rcov.rake"
  ]
  s.homepage = %q{http://github.com/invernizzi/rcov_plugin}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{The easiest way to measure coverage for your Rails project}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0.beta2"])
      s.add_runtime_dependency(%q<rcov>, [">= 0.9.6"])
    else
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3.0.0.beta2"])
      s.add_dependency(%q<rcov>, [">= 0.9.6"])
    end
  else
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3.0.0.beta2"])
    s.add_dependency(%q<rcov>, [">= 0.9.6"])
  end
end

